In [1]:
print("hello world")

hello world


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)

[5 7 9]


In [3]:
menu = np.array(['cheese', 'bbq', 'veg', 'spicy'])
print(menu)

['cheese' 'bbq' 'veg' 'spicy']


In [4]:
prices_np = np.array([100, 200, 150, 222])
prices = prices_np * 0.8
print(prices)

[ 80.  160.  120.  177.6]


In [5]:
empty_table = np.zeros((2,3))
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
full_table = np.ones((3,3))
print(full_table)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
bbq_boxes = np.full((2,3), 'bbq')
print(bbq_boxes)

[['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [4]:
kids_order = np.random.randint(1, 8, (2,3))
print(kids_order)

[[4 1 1]
 [2 4 2]]


In [5]:
surpise_topping = np.random.rand(2,3)
print(surpise_topping)

[[0.74105795 0.02170665 0.20893013]
 [0.5877416  0.34388495 0.81147471]]


In [6]:
signature_prizzas = np.identity(4)
print(signature_prizzas)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
delivery_time = np.arange(0, 70, 15)
print(delivery_time)

[ 0 15 30 45 60]
