In [1]:
print("hello world")

hello world


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)

[5 7 9]


In [3]:
menu = np.array(['cheese', 'bbq', 'veg', 'spicy'])
print(menu)

['cheese' 'bbq' 'veg' 'spicy']


In [4]:
prices_np = np.array([100, 200, 150, 222])
prices = prices_np * 0.8
print(prices)

[ 80.  160.  120.  177.6]


In [5]:
empty_table = np.zeros((2,3))
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
full_table = np.ones((3,3))
print(full_table)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
