In [ ]:
print("hello world")

hello world


In [81]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)

[5 7 9]


In [82]:
menu = np.array(['cheese', 'bbq', 'veg', 'spicy'])
print(menu)

['cheese' 'bbq' 'veg' 'spicy']


In [83]:
prices_np = np.array([100, 200, 150, 222])
prices = prices_np * 0.8
print(prices)

[ 80.  160.  120.  177.6]


In [84]:
empty_table = np.zeros((2,3))
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]]


In [85]:
full_table = np.ones((3,3))
print(full_table)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [86]:
bbq_boxes = np.full((2,3), 'bbq')
print(bbq_boxes)

[['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [87]:
kids_order = np.random.randint(1, 8, (2,3))
print(kids_order)

[[3 4 6]
 [6 5 6]]


In [88]:
surpise_topping = np.random.rand(2,3)
print(surpise_topping)

[[0.13826495 0.5461166  0.29975794]
 [0.75525037 0.21030021 0.1142039 ]]


In [89]:
signature_prizzas = np.identity(4)
print(signature_prizzas)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [90]:
delivery_time = np.arange(0, 70, 15)
print(delivery_time)

[ 0 15 30 45 60]


In [91]:
cooking_shifts = np.linspace(0, 7, 5)
print(cooking_shifts)

[0.   1.75 3.5  5.25 7.  ]


In [92]:
orders = np.array(['cheese', 'veg', 'spicy', 'bby'])
print(orders[2])

spicy


In [93]:
print(orders[1:3])

['veg' 'spicy']


In [94]:
orders = np.array([
    ['cheese', 'veg', 'veg'],
    ['spicy', 'bby', 'spicy']
    ])
print(orders[1, 0])

spicy


In [95]:
print(orders[:, 0])

['cheese' 'spicy']


In [96]:
print(orders[:, 1])

['veg' 'bby']


In [97]:
print(orders[0, :])

['cheese' 'veg' 'veg']


In [98]:
print(orders[0, 1:3])

['veg' 'veg']


In [99]:
print(orders[:, 1:3])

[['veg' 'veg']
 ['bby' 'spicy']]


In [100]:
sales = np.array([2000, 1500, 8000, 3500])
print("Max sales index", np.argmax(sales))
print("Max sales index", np.max(sales))
print("Max sales index", np.argmin(sales))

Max sales index 2
Max sales index 8000
Max sales index 1


In [101]:
array = np.arange(0,25)
array = array.reshape(5,5)
print(array)
print(array.shape)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [102]:
array = np.arange(0.1, 2.6, 0.1).reshape(5, 5)
print(array)


[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]
 [2.1 2.2 2.3 2.4 2.5]]


In [ ]:
array = np.linspace(0, 24, num=25, dtype=int).reshape(5, 5)
print(array)

In [ ]:
matrix = np.identity(5) * 5
print(matrix)

In [ ]:
number = np.random.randint(10)
print(number)